/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#7c2e00",
        "on-secondary-fixed": "#001a41",
        "tertiary": "#ffb695",
        "on-secondary-container": "#9bb8f6",
        "tertiary-fixed": "#ffdbcc",
        "on-surface-variant": "#c1c6d7",
        "on-primary-fixed-variant": "#004493",
        "surface-container-lowest": "#0c0e10",
        "inverse-primary": "#005bc0",
        "primary": "#adc7ff",
        "on-tertiary-container": "#4c1a00",
        "error-container": "#93000a",
        "secondary-container": "#29487f",
        "surface-variant": "#333537",
        "tertiary-container": "#ef6719",
        "primary-container": "#4a8eff",
        "on-primary-fixed": "#001a41",
        "on-secondary": "#072f64",
        "tertiary-fixed-dim": "#ffb695",
        "on-error-container": "#ffdad6",
        "surface-container": "#1e2022",
        "on-error": "#690005",
        "surface-tint": "#adc7ff",
        "surface-container-highest": "#333537",
        "outline-variant": "#414754",
        "surface-dim": "#121416",
        "outline": "#8b90a0",
        "on-secondary-fixed-variant": "#26467c",
        "surface-bright": "#37393b",
        "on-tertiary": "#571e00",
        "background": "#121416",
        "on-tertiary-fixed": "#351000",
        "secondary-fixed-dim": "#adc7ff",
        "secondary": "#adc7ff",
        "inverse-on-surface": "#2f3133",
        "inverse-surface": "#e2e2e5",
        "surface": "#121416",
        "on-background": "#e2e2e5",
        "surface-container-high": "#282a2c",
        "secondary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc7ff",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#e2e2e5",
        "on-primary-container": "#00285b",
        "on-primary": "#002e68",
        "surface-container-low": "#1a1c1e"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
